/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradschoolportal;

import javax.swing.JOptionPane;

/**
 *
 * @author muham
 */
public class Add_Degree extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_Degree
     */
    public Add_Degree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_title_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        degree_code = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        grad_school = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        degree_forecast = new javax.swing.JTextField();
        add_degree = new javax.swing.JButton();
        cancel_degree = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        degree_name = new javax.swing.JTextArea();
        code_error = new javax.swing.JLabel();
        school_error = new javax.swing.JLabel();
        name_error = new javax.swing.JLabel();
        forecast_error = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(480, 440));

        login_title_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        login_title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title_label.setText("Oklahoma Christian University");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Degree");

        jLabel2.setText("Degree Code:");

        degree_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                degree_codeKeyReleased(evt);
            }
        });

        jLabel3.setText("Grad School: ");

        grad_school.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grad_schoolKeyReleased(evt);
            }
        });

        jLabel5.setText("Degree Name: ");

        jLabel6.setText("Forecast:");

        degree_forecast.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                degree_forecastKeyReleased(evt);
            }
        });

        add_degree.setText("Add");
        add_degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_degreeActionPerformed(evt);
            }
        });

        cancel_degree.setText("Cancel");
        cancel_degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_degreeActionPerformed(evt);
            }
        });

        degree_name.setColumns(20);
        degree_name.setRows(5);
        degree_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                degree_nameKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(degree_name);

        code_error.setForeground(new java.awt.Color(255, 0, 0));

        school_error.setForeground(new java.awt.Color(255, 0, 0));

        name_error.setForeground(new java.awt.Color(255, 0, 0));

        forecast_error.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grad_school, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(degree_code, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(degree_forecast))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(add_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancel_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(code_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(school_error, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(name_error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(forecast_error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(login_title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degree_code, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_error))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grad_school, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(school_error))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degree_forecast, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forecast_error))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void degree_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degree_codeKeyReleased
        // TODO add your handling code here:
        if (degree_code.getText().equals("")) {

        } else {
            code_error.setText("");
        }
    }//GEN-LAST:event_degree_codeKeyReleased

    private void grad_schoolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grad_schoolKeyReleased
        // TODO add your handling code here:
        if (grad_school.getText().equals("")) {

        } else {
            school_error.setText("");
        }
    }//GEN-LAST:event_grad_schoolKeyReleased

    private void degree_forecastKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degree_forecastKeyReleased
        // TODO add your handling code here:
        if (degree_forecast.getText().equals("")) {

        } else {
            forecast_error.setText("");
        }
    }//GEN-LAST:event_degree_forecastKeyReleased

    private void add_degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_degreeActionPerformed
        // TODO add your handling code here:
        String code = degree_code.getText();
        if (code.equals("")) {
            code_error.setText("*Required");
        } else {
            String school = grad_school.getText();
            if (school.equals("")) {
                school_error.setText("*Required");
            } else {
                String name = degree_name.getText();
                if (name.equals("")) {
                    name_error.setText("*Required");
                } else {
                    String forecast = degree_forecast.getText();
                    if (forecast.equals("")) {
                        forecast_error.setText("*Required");
                    } else {
                        Degree_Info_Class dicObj = new Degree_Info_Class();
                        if (dicObj.add_degree(code, school, name, forecast)) {
                            JOptionPane.showMessageDialog(rootPane, "Degree added successfully.");
                            degree_code.setText("");
                            grad_school.setText("");
                            degree_name.setText("");
                            degree_forecast.setText("");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_add_degreeActionPerformed

    private void cancel_degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_degreeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancel_degreeActionPerformed

    private void degree_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degree_nameKeyReleased
        // TODO add your handling code here:
        if (degree_name.getText().equals("")) {

        } else {
            name_error.setText("");
        }
    }//GEN-LAST:event_degree_nameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add_degree;
    public javax.swing.JButton cancel_degree;
    public javax.swing.JLabel code_error;
    public javax.swing.JTextField degree_code;
    public javax.swing.JTextField degree_forecast;
    public javax.swing.JTextArea degree_name;
    public javax.swing.JLabel forecast_error;
    public javax.swing.JTextField grad_school;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel login_title_label;
    public javax.swing.JLabel name_error;
    public javax.swing.JLabel school_error;
    // End of variables declaration//GEN-END:variables
}
