
package gradschoolportal;

import java.awt.Dimension;

public class Director_Panel extends javax.swing.JFrame {

    int user_id;
    
    /**
     * Creates new form Director_Panel
     */
    public Director_Panel() {
        initComponents();
    }
    
    public Director_Panel(int user_id){
        initComponents();
        this.user_id = user_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        director_desktop = new javax.swing.JDesktopPane();
        director_panel_menu = new javax.swing.JMenuBar();
        director_panel_menu_file = new javax.swing.JMenu();
        director_panel_menu_file_main_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        director_desktop.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout director_desktopLayout = new javax.swing.GroupLayout(director_desktop);
        director_desktop.setLayout(director_desktopLayout);
        director_desktopLayout.setHorizontalGroup(
            director_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        director_desktopLayout.setVerticalGroup(
            director_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        director_panel_menu_file.setText("File");

        director_panel_menu_file_main_menu.setText("Main Menu");
        director_panel_menu_file_main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                director_panel_menu_file_main_menuActionPerformed(evt);
            }
        });
        director_panel_menu_file.add(director_panel_menu_file_main_menu);

        director_panel_menu.add(director_panel_menu_file);

        setJMenuBar(director_panel_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(director_desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(director_desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void director_panel_menu_file_main_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_director_panel_menu_file_main_menuActionPerformed
        // TODO add your handling code here:
        Director_Main_Menu dmmObj = new Director_Main_Menu(user_id);
        director_desktop.add(dmmObj);
        Dimension dt = director_desktop.getSize();
        Dimension dmm = dmmObj.getSize();
        dmmObj.setLocation((dt.width - dmm.width) / 2, (dt.height - dmm.height) / 2);
        dmmObj.setVisible(true);
        
    }//GEN-LAST:event_director_panel_menu_file_main_menuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Director_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Director_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Director_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Director_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Director_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane director_desktop;
    public javax.swing.JMenuBar director_panel_menu;
    public javax.swing.JMenu director_panel_menu_file;
    public javax.swing.JMenuItem director_panel_menu_file_main_menu;
    // End of variables declaration//GEN-END:variables
}
