/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradschoolportal;

import java.awt.Dimension;
import java.awt.Window;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public class Faculty_Info extends javax.swing.JInternalFrame {

    int user_id;
    String lname = "";
    String fname = "";
    String school = "";
    String rtitle = "";
    /**
     * Creates new form Faculty_Info
     */
    public Faculty_Info() {
        initComponents();
    }
    
    public Faculty_Info(int user_id) {
        initComponents();
        this.user_id = user_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_menu = new javax.swing.JButton();
        director_logout = new javax.swing.JLabel();
        login_title_label = new javax.swing.JLabel();
        student_info = new javax.swing.JButton();
        refersh_faculty = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        courses_info = new javax.swing.JButton();
        faculty_info = new javax.swing.JButton();
        degree_info = new javax.swing.JButton();
        personal_info = new javax.swing.JButton();
        add_faculty = new javax.swing.JButton();
        update_faculty = new javax.swing.JButton();
        delete_faculty = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        faculty_table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Faculty Information");
        setPreferredSize(new java.awt.Dimension(640, 480));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        main_menu.setBackground(new java.awt.Color(51, 153, 255));
        main_menu.setText("Main Menu");
        main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menuActionPerformed(evt);
            }
        });

        director_logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        director_logout.setText("<HTML><a href=\"\">User : Sign Out</a></HTML>");
        director_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        director_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                director_logoutMouseClicked(evt);
            }
        });

        login_title_label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        login_title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title_label.setText("Oklahoma Christian University");

        student_info.setBackground(new java.awt.Color(51, 153, 255));
        student_info.setText("Student Info");
        student_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_infoActionPerformed(evt);
            }
        });

        refersh_faculty.setText("Refersh");
        refersh_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refersh_facultyActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Faculty Member:");

        courses_info.setBackground(new java.awt.Color(51, 153, 255));
        courses_info.setText("Courses Info");
        courses_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses_infoActionPerformed(evt);
            }
        });

        faculty_info.setBackground(new java.awt.Color(51, 153, 255));
        faculty_info.setText("Faculty Info");
        faculty_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faculty_infoActionPerformed(evt);
            }
        });

        degree_info.setBackground(new java.awt.Color(51, 153, 255));
        degree_info.setText("Degree Info");
        degree_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree_infoActionPerformed(evt);
            }
        });

        personal_info.setBackground(new java.awt.Color(51, 153, 255));
        personal_info.setText("Personal Info");
        personal_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_infoActionPerformed(evt);
            }
        });

        add_faculty.setBackground(new java.awt.Color(51, 153, 255));
        add_faculty.setText("Add");
        add_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_facultyActionPerformed(evt);
            }
        });

        update_faculty.setBackground(new java.awt.Color(0, 153, 102));
        update_faculty.setText("Update");
        update_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_facultyActionPerformed(evt);
            }
        });

        delete_faculty.setBackground(new java.awt.Color(255, 0, 0));
        delete_faculty.setText("Delete");
        delete_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_facultyActionPerformed(evt);
            }
        });

        faculty_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        faculty_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faculty_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(faculty_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_title_label, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(main_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(courses_info, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(faculty_info, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(degree_info, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(personal_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(director_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(refersh_faculty))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(add_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(update_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(delete_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(student_info, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(director_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(student_info, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refersh_faculty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courses_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(faculty_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(degree_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(personal_info, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delete_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menuActionPerformed
        // TODO add your handling code here:
        Login_Class lcObj = new Login_Class();
        lcObj.verify(user_id);
        String type = lcObj.type;
        if (type.equals("Director")) {
            Director_Main_Menu dmmObj = new Director_Main_Menu(user_id);
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(dmmObj);
            Dimension dt = desktop.getSize();
            Dimension dmm = dmmObj.getSize();
            dmmObj.setLocation((dt.width - dmm.width) / 2, (dt.height - dmm.height) / 2);
            dmmObj.setVisible(true);
            this.dispose();
        } else {
            Admin_Main_Menu ammObj = new Admin_Main_Menu(user_id);
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(ammObj);
            Dimension dt = desktop.getSize();
            Dimension amm = ammObj.getSize();
            ammObj.setLocation((dt.width - amm.width) / 2, (dt.height - amm.height) / 2);
            ammObj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_main_menuActionPerformed

    private void director_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_director_logoutMouseClicked
        // TODO add your handling code here:
        Window win[] = java.awt.Window.getWindows();
        for (Window win1 : win) {
            win1.dispose();
        }
        Login_Form lfObj = new Login_Form();
        lfObj.setLocationRelativeTo(null);
        lfObj.pack();
        lfObj.setVisible(true);
    }//GEN-LAST:event_director_logoutMouseClicked

    private void student_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_infoActionPerformed
        // TODO add your handling code here:
        Student_Info siObj = new Student_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(siObj);
        Dimension si = siObj.getSize();
        Dimension dt = desktop.getSize();
        siObj.setLocation((dt.width - si.width) / 2, (dt.height - si.height) / 2);
        siObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_student_infoActionPerformed

    private void refersh_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refersh_facultyActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = new Faculty_Info_Class().get_faculty();
        faculty_table.setModel(dm);
    }//GEN-LAST:event_refersh_facultyActionPerformed

    private void courses_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses_infoActionPerformed
        // TODO add your handling code here:
        Courses_Info ciObj = new Courses_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(ciObj);
        Dimension dt = desktop.getSize();
        Dimension ci = ciObj.getSize();
        ciObj.setLocation((dt.width - ci.width) / 2, (dt.height - ci.height) / 2);
        ciObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_courses_infoActionPerformed

    private void faculty_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faculty_infoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faculty_infoActionPerformed

    private void degree_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree_infoActionPerformed
        // TODO add your handling code here:
        Degree_Info diObj = new Degree_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(diObj);
        Dimension dt = desktop.getSize();
        Dimension di = diObj.getSize();
        diObj.setLocation((dt.width - di.width) / 2, (dt.height - di.height) / 2);
        diObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_degree_infoActionPerformed

    private void personal_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_infoActionPerformed
        // TODO add your handling code here:
        Personal_Info piObj = new Personal_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(piObj);
        Dimension dt = desktop.getSize();
        Dimension di = piObj.getSize();
        piObj.setLocation((dt.width - di.width) / 2, (dt.height - di.height) / 2);
        piObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_personal_infoActionPerformed

    private void add_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_facultyActionPerformed
        // TODO add your handling code here:
        Add_Faculty afObj = new Add_Faculty();
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(afObj);
        Dimension dt = desktop.getSize();
        Dimension ac = afObj.getSize();
        afObj.setLocation((dt.width - ac.width) / 2, (dt.height - ac.height) / 2);
        afObj.setVisible(true);
    }//GEN-LAST:event_add_facultyActionPerformed

    private void update_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_facultyActionPerformed
        // TODO add your handling code here:
        if (lname.equals("") || fname.equals("") || school.equals("") || rtitle.equals("")) {
            JOptionPane.showMessageDialog(director_logout, "Please select a member to update.");
        } else {
            Update_Faculty ufObj = new Update_Faculty(lname, fname, school, title);
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(ufObj);
            Dimension dt = desktop.getSize();
            Dimension uc = ufObj.getSize();
            ufObj.setLocation((dt.width - uc.width) / 2, (dt.height - uc.height) / 2);
            ufObj.setVisible(true);
        }
    }//GEN-LAST:event_update_facultyActionPerformed

    private void delete_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_facultyActionPerformed
        // TODO add your handling code here:
        if (lname.equals("") || fname.equals("") || school.equals("") || rtitle.equals("")) {
            JOptionPane.showMessageDialog(null, "Please select a member to delete.");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the faculty member?");
            if (confirm == JOptionPane.YES_OPTION) {
                Faculty_Info_Class ficObj = new Faculty_Info_Class();
                if (ficObj.delete_faculty(lname, fname, school)) {
                    JOptionPane.showMessageDialog(null, "Course deleted.");
                    DefaultTableModel dm = new Faculty_Info_Class().get_faculty();
                    faculty_table.setModel(dm);
                }
            }
        }
    }//GEN-LAST:event_delete_facultyActionPerformed

    private void faculty_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faculty_tableMouseClicked
        // TODO add your handling code here:
        lname = faculty_table.getValueAt(faculty_table.getSelectedRow(), 0).toString();
        fname = faculty_table.getValueAt(faculty_table.getSelectedRow(), 1).toString();
        school = faculty_table.getValueAt(faculty_table.getSelectedRow(), 2).toString();
        rtitle = faculty_table.getValueAt(faculty_table.getSelectedRow(), 3).toString();
    }//GEN-LAST:event_faculty_tableMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DefaultTableModel dm = new Faculty_Info_Class().get_faculty();
        faculty_table.setModel(dm);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add_faculty;
    public javax.swing.JButton courses_info;
    public javax.swing.JButton degree_info;
    public javax.swing.JButton delete_faculty;
    public javax.swing.JLabel director_logout;
    public javax.swing.JButton faculty_info;
    public javax.swing.JTable faculty_table;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel login_title_label;
    public javax.swing.JButton main_menu;
    public javax.swing.JButton personal_info;
    public javax.swing.JButton refersh_faculty;
    public javax.swing.JButton student_info;
    public javax.swing.JButton update_faculty;
    // End of variables declaration//GEN-END:variables
}
