/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradschoolportal;

import java.awt.Dimension;
import java.awt.Window;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public class Generate_Schedule extends javax.swing.JInternalFrame {

    int user_id;
    String username;
    String term;
    String atitle;

    /**
     * Creates new form Generate_Schedule
     */
    public Generate_Schedule() {
        initComponents();
    }

    public Generate_Schedule(int user_id) {
        initComponents();
        this.user_id = user_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_menu = new javax.swing.JButton();
        director_logout = new javax.swing.JLabel();
        login_title_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        refersh_schedule = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        schedule_Table = new javax.swing.JTable();
        add_schedule = new javax.swing.JButton();
        update_schedule = new javax.swing.JButton();
        delete_schedule = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        main_menu.setBackground(new java.awt.Color(51, 153, 255));
        main_menu.setText("Main Menu");
        main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menuActionPerformed(evt);
            }
        });

        director_logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        director_logout.setText("<HTML><a href=\"\">User : Sign Out</a></HTML>");
        director_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        director_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                director_logoutMouseClicked(evt);
            }
        });

        login_title_label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        login_title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title_label.setText("Oklahoma Christian University");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Choose Schedule:");

        refersh_schedule.setText("Refresh");
        refersh_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refersh_scheduleActionPerformed(evt);
            }
        });

        schedule_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schedule_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(schedule_Table);

        add_schedule.setText("Add");
        add_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_scheduleActionPerformed(evt);
            }
        });

        update_schedule.setText("Update");
        update_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_scheduleActionPerformed(evt);
            }
        });

        delete_schedule.setText("Delete");
        delete_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_scheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(director_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(add_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login_title_label, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refersh_schedule)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(director_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(login_title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refersh_schedule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(update_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(add_schedule, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menuActionPerformed
        // TODO add your handling code here:
        Director_Main_Menu dmmObj = new Director_Main_Menu(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(dmmObj);
        Dimension dt = desktop.getSize();
        Dimension dmm = dmmObj.getSize();
        dmmObj.setLocation((dt.width - dmm.width) / 2, (dt.height - dmm.height) / 2);
        dmmObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_main_menuActionPerformed

    private void director_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_director_logoutMouseClicked
        // TODO add your handling code here:
        Window win[] = java.awt.Window.getWindows();
        for (Window win1 : win) {
            win1.dispose();
        }
        Login_Form lfObj = new Login_Form();
        lfObj.setLocationRelativeTo(null);
        lfObj.pack();
        lfObj.setVisible(true);
    }//GEN-LAST:event_director_logoutMouseClicked

    private void refersh_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refersh_scheduleActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = new Generate_Schedule_Class().get_schedule();
        schedule_Table.setModel(dm);
    }//GEN-LAST:event_refersh_scheduleActionPerformed

    private void schedule_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedule_TableMouseClicked
        // TODO add your handling code here:
        term = schedule_Table.getValueAt(schedule_Table.getSelectedRow(), 0).toString();
        atitle = schedule_Table.getValueAt(schedule_Table.getSelectedRow(), 2).toString();
    }//GEN-LAST:event_schedule_TableMouseClicked

    private void add_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_scheduleActionPerformed
        // TODO add your handling code here:
        Add_Schedule asObj = new Add_Schedule();
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(asObj);
        Dimension dt = desktop.getSize();
        Dimension dmm = asObj.getSize();
        asObj.setLocation((dt.width - dmm.width) / 2, (dt.height - dmm.height) / 2);
        asObj.setVisible(true);
    }//GEN-LAST:event_add_scheduleActionPerformed

    private void update_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_scheduleActionPerformed
        // TODO add your handling code here:
        if (term.equals("")) {
            JOptionPane.showMessageDialog(null, "Please select a schedule to update.");
        } else {
            Update_Schedule usObj = new Update_Schedule(term, atitle);
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(usObj);
            Dimension dt = desktop.getSize();
            Dimension dmm = usObj.getSize();
            usObj.setLocation((dt.width - dmm.width) / 2, (dt.height - dmm.height) / 2);
            usObj.setVisible(true);
        }
    }//GEN-LAST:event_update_scheduleActionPerformed

    private void delete_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_scheduleActionPerformed
        // TODO add your handling code here:
        if (term.equals("")) {
            JOptionPane.showMessageDialog(null, "Please select a schedule to delete.");
        } else {
            Generate_Schedule_Class gscObj = new Generate_Schedule_Class();
            if (gscObj.delete_schedule(term, title)) {
                JOptionPane.showMessageDialog(director_logout, "Schedule deleted.");
                DefaultTableModel dm = gscObj.get_schedule();
                schedule_Table.setModel(dm);
            } else {
                JOptionPane.showMessageDialog(director_logout, "Error while trying to delete Schedule.");
            }
        }
    }//GEN-LAST:event_delete_scheduleActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DefaultTableModel dm = new Generate_Schedule_Class().get_schedule();
        schedule_Table.setModel(dm);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add_schedule;
    public javax.swing.JButton delete_schedule;
    public javax.swing.JLabel director_logout;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel login_title_label;
    public javax.swing.JButton main_menu;
    public javax.swing.JButton refersh_schedule;
    public javax.swing.JTable schedule_Table;
    public javax.swing.JButton update_schedule;
    // End of variables declaration//GEN-END:variables
}
