/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradschoolportal;

import java.awt.Dimension;
import java.awt.Window;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public class Personal_Info extends javax.swing.JInternalFrame {
    
    int user_id;

    /**
     * Creates new form Personal_Info
     */
    public Personal_Info() {
        initComponents();
    }
    
    public Personal_Info(int user_id) {
        initComponents();
        this.user_id = user_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_menu = new javax.swing.JButton();
        director_logout = new javax.swing.JLabel();
        login_title_label = new javax.swing.JLabel();
        student_info = new javax.swing.JButton();
        courses_info = new javax.swing.JButton();
        faculty_info = new javax.swing.JButton();
        degree_info = new javax.swing.JButton();
        personal_info = new javax.swing.JButton();
        update_user = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        user_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        user_password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        user_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        user_phone = new javax.swing.JTextField();
        name_error = new javax.swing.JLabel();
        username_error = new javax.swing.JLabel();
        password_error = new javax.swing.JLabel();
        email_error = new javax.swing.JLabel();
        phone_error = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(640, 480));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        main_menu.setBackground(new java.awt.Color(51, 153, 255));
        main_menu.setText("Main Menu");
        main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menuActionPerformed(evt);
            }
        });

        director_logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        director_logout.setText("<HTML><a href=\"\">User : Sign Out</a></HTML>");
        director_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        director_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                director_logoutMouseClicked(evt);
            }
        });

        login_title_label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        login_title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title_label.setText("Oklahoma Christian University");

        student_info.setBackground(new java.awt.Color(51, 153, 255));
        student_info.setText("Student Info");
        student_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_infoActionPerformed(evt);
            }
        });

        courses_info.setBackground(new java.awt.Color(51, 153, 255));
        courses_info.setText("Courses Info");
        courses_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses_infoActionPerformed(evt);
            }
        });

        faculty_info.setBackground(new java.awt.Color(51, 153, 255));
        faculty_info.setText("Faculty Info");
        faculty_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faculty_infoActionPerformed(evt);
            }
        });

        degree_info.setBackground(new java.awt.Color(51, 153, 255));
        degree_info.setText("Degree Info");
        degree_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree_infoActionPerformed(evt);
            }
        });

        personal_info.setBackground(new java.awt.Color(51, 153, 255));
        personal_info.setText("Personal Info");
        personal_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_infoActionPerformed(evt);
            }
        });

        update_user.setBackground(new java.awt.Color(0, 153, 102));
        update_user.setText("Update");
        update_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_userActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        user_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_nameKeyReleased(evt);
            }
        });

        jLabel2.setText("Username: ");

        user_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_usernameKeyReleased(evt);
            }
        });

        jLabel3.setText("Password: ");

        user_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_passwordKeyReleased(evt);
            }
        });

        jLabel4.setText("Email: ");

        user_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_emailKeyReleased(evt);
            }
        });

        jLabel5.setText("Phone:");

        user_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_phoneKeyReleased(evt);
            }
        });

        name_error.setForeground(new java.awt.Color(255, 0, 0));

        username_error.setForeground(new java.awt.Color(255, 0, 0));

        password_error.setForeground(new java.awt.Color(255, 0, 0));

        email_error.setForeground(new java.awt.Color(255, 0, 0));

        phone_error.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_title_label, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(main_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(courses_info, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(faculty_info, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(degree_info, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(personal_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(director_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(update_user, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(user_email, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(user_password, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(password_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(email_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(118, 118, 118)
                                                .addComponent(user_username, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(user_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(username_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(phone_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(student_info, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(name_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(director_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(student_info, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_error))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courses_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faculty_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degree_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personal_info, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_error))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menuActionPerformed
        // TODO add your handling code here:
        Login_Class lcObj = new Login_Class();
        lcObj.verify(user_id);
        String type = lcObj.type;
        if (type.equals("Director")) {
            Director_Main_Menu dmmObj = new Director_Main_Menu(user_id);
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(dmmObj);
            Dimension dt = desktop.getSize();
            Dimension dmm = dmmObj.getSize();
            dmmObj.setLocation((dt.width - dmm.width) / 2, (dt.height - dmm.height) / 2);
            dmmObj.setVisible(true);
            this.dispose();
        } else {
            Admin_Main_Menu ammObj = new Admin_Main_Menu(user_id);
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(ammObj);
            Dimension dt = desktop.getSize();
            Dimension amm = ammObj.getSize();
            ammObj.setLocation((dt.width - amm.width) / 2, (dt.height - amm.height) / 2);
            ammObj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_main_menuActionPerformed

    private void director_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_director_logoutMouseClicked
        // TODO add your handling code here:
        Window win[] = java.awt.Window.getWindows();
        for (Window win1 : win) {
            win1.dispose();
        }
        Login_Form lfObj = new Login_Form();
        lfObj.setLocationRelativeTo(null);
        lfObj.pack();
        lfObj.setVisible(true);
    }//GEN-LAST:event_director_logoutMouseClicked

    private void student_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_infoActionPerformed
        // TODO add your handling code here:
        Student_Info siObj = new Student_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(siObj);
        Dimension si = siObj.getSize();
        Dimension dt = desktop.getSize();
        siObj.setLocation((dt.width - si.width) / 2, (dt.height - si.height) / 2);
        siObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_student_infoActionPerformed

    private void courses_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses_infoActionPerformed
        // TODO add your handling code here:
        Courses_Info ciObj = new Courses_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(ciObj);
        Dimension dt = desktop.getSize();
        Dimension ci = ciObj.getSize();
        ciObj.setLocation((dt.width - ci.width) / 2, (dt.height - ci.height) / 2);
        ciObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_courses_infoActionPerformed

    private void faculty_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faculty_infoActionPerformed
        // TODO add your handling code here:
        Faculty_Info fiObj = new Faculty_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(fiObj);
        Dimension dt = desktop.getSize();
        Dimension ci = fiObj.getSize();
        fiObj.setLocation((dt.width - ci.width) / 2, (dt.height - ci.height) / 2);
        fiObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_faculty_infoActionPerformed

    private void degree_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree_infoActionPerformed
        // TODO add your handling code here:
        Degree_Info diObj = new Degree_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(diObj);
        Dimension dt = desktop.getSize();
        Dimension di = diObj.getSize();
        diObj.setLocation((dt.width - di.width) / 2, (dt.height - di.height) / 2);
        diObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_degree_infoActionPerformed

    private void personal_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_infoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_infoActionPerformed

    private void update_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_userActionPerformed
        // TODO add your handling code here:
        String name = user_name.getText();
        if (name.equals("")) {
            name_error.setText("*Required");
        } else {
            String username = user_username.getText();
            if (username.equals("")) {
                username_error.setText("*Required");
            } else {
                String password = user_password.getText();
                if (password.equals("")) {
                    password_error.setText("*Required");
                } else {
                    String email = user_email.getText();
                    if (email.equals("")) {
                        email_error.setText("*Required");
                    } else {
                        String phone = user_phone.getText();
                        if (phone.equals("")) {
                            phone_error.setText("*Required");
                        } else {
                            Personal_Info_Class picObj = new Personal_Info_Class();
                            if(picObj.update(user_id, name, username, password, email, phone)){
                                JOptionPane.showMessageDialog(director_logout, "Information Updated.");
                            }
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_update_userActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Personal_Info_Class picObj = new Personal_Info_Class();
        picObj.edit(user_id);
        user_name.setText(picObj.name);
        user_username.setText(picObj.username);
        user_password.setText(picObj.password);
        user_email.setText(picObj.email);
        user_phone.setText(picObj.phone);
    }//GEN-LAST:event_formInternalFrameOpened

    private void user_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_nameKeyReleased
        // TODO add your handling code here:
        if (user_name.getText().equals("")) {
            
        } else {
            name_error.setText("");
        }
    }//GEN-LAST:event_user_nameKeyReleased

    private void user_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_usernameKeyReleased
        // TODO add your handling code here:
        if (user_username.getText().equals("")) {
            
        } else {
            username_error.setText("");
        }
    }//GEN-LAST:event_user_usernameKeyReleased

    private void user_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_passwordKeyReleased
        // TODO add your handling code here:
        if (user_password.getText().equals("")) {
            
        } else {
            password_error.setText("");
        }
    }//GEN-LAST:event_user_passwordKeyReleased

    private void user_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_emailKeyReleased
        // TODO add your handling code here:
        if (user_email.getText().equals("")) {
            
        } else {
            email_error.setText("");
        }
    }//GEN-LAST:event_user_emailKeyReleased

    private void user_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_phoneKeyReleased
        // TODO add your handling code here:
        if (user_phone.getText().equals("")) {
            
        } else {
            phone_error.setText("");
        }
    }//GEN-LAST:event_user_phoneKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton courses_info;
    public javax.swing.JButton degree_info;
    public javax.swing.JLabel director_logout;
    public javax.swing.JLabel email_error;
    public javax.swing.JButton faculty_info;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel login_title_label;
    public javax.swing.JButton main_menu;
    public javax.swing.JLabel name_error;
    public javax.swing.JLabel password_error;
    public javax.swing.JButton personal_info;
    public javax.swing.JLabel phone_error;
    public javax.swing.JButton student_info;
    public javax.swing.JButton update_user;
    public javax.swing.JTextField user_email;
    public javax.swing.JTextField user_name;
    public javax.swing.JTextField user_password;
    public javax.swing.JTextField user_phone;
    public javax.swing.JTextField user_username;
    public javax.swing.JLabel username_error;
    // End of variables declaration//GEN-END:variables
}
