package gradschoolportal;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Window;
import java.io.*;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Student_Info extends javax.swing.JInternalFrame {

    int user_id;
    public File stu_file;
    public File stc_file;
    String stu_file_path;
    String stc_file_path;

    /**
     * Creates new form Student_Info
     */
    public Student_Info() {
        initComponents();
    }
    
    public Student_Info(int user_id) {
        initComponents();
        this.user_id = user_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stu_file_chooser = new javax.swing.JFileChooser();
        stc_file_chooser = new javax.swing.JFileChooser();
        main_menu = new javax.swing.JButton();
        director_logout = new javax.swing.JLabel();
        student_info = new javax.swing.JButton();
        courses_info = new javax.swing.JButton();
        faculty_info = new javax.swing.JButton();
        degree_info = new javax.swing.JButton();
        personal_info = new javax.swing.JButton();
        login_title_label = new javax.swing.JLabel();
        stu_label = new javax.swing.JLabel();
        stu_file_name = new javax.swing.JTextField();
        stu_file_browse = new javax.swing.JButton();
        stc_label = new javax.swing.JLabel();
        stc_file_name = new javax.swing.JTextField();
        stc_file_browse = new javax.swing.JButton();
        save_files = new javax.swing.JButton();
        cancel_files = new javax.swing.JButton();
        stu_file_error = new javax.swing.JLabel();
        stc_file_error = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Student Information");
        setPreferredSize(new java.awt.Dimension(640, 480));

        main_menu.setBackground(new java.awt.Color(51, 153, 255));
        main_menu.setText("Main Menu");
        main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menuActionPerformed(evt);
            }
        });

        director_logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        director_logout.setText("<HTML><a href=\"\">User : Sign Out</a></HTML>");
        director_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        director_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                director_logoutMouseClicked(evt);
            }
        });

        student_info.setBackground(new java.awt.Color(51, 153, 255));
        student_info.setText("Student Info");
        student_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_infoActionPerformed(evt);
            }
        });

        courses_info.setBackground(new java.awt.Color(51, 153, 255));
        courses_info.setText("Courses Info");
        courses_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courses_infoActionPerformed(evt);
            }
        });

        faculty_info.setBackground(new java.awt.Color(51, 153, 255));
        faculty_info.setText("Faculty Info");
        faculty_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faculty_infoActionPerformed(evt);
            }
        });

        degree_info.setBackground(new java.awt.Color(51, 153, 255));
        degree_info.setText("Degree Info");
        degree_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree_infoActionPerformed(evt);
            }
        });

        personal_info.setBackground(new java.awt.Color(51, 153, 255));
        personal_info.setText("Personal Info");
        personal_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_infoActionPerformed(evt);
            }
        });

        login_title_label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        login_title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title_label.setText("Oklahoma Christian University");

        stu_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stu_label.setText("Student Info:");

        stu_file_name.setEnabled(false);

        stu_file_browse.setBackground(new java.awt.Color(0, 153, 102));
        stu_file_browse.setText("Browse");
        stu_file_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_file_browseActionPerformed(evt);
            }
        });

        stc_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stc_label.setText("Student Course:");

        stc_file_name.setEnabled(false);

        stc_file_browse.setBackground(new java.awt.Color(0, 153, 102));
        stc_file_browse.setText("Browse");
        stc_file_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stc_file_browseActionPerformed(evt);
            }
        });

        save_files.setBackground(new java.awt.Color(51, 153, 255));
        save_files.setText("Save");
        save_files.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_filesActionPerformed(evt);
            }
        });

        cancel_files.setBackground(new java.awt.Color(255, 0, 0));
        cancel_files.setText("Cancel");
        cancel_files.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_filesActionPerformed(evt);
            }
        });

        stu_file_error.setForeground(new java.awt.Color(255, 0, 0));
        stu_file_error.setText(" ");

        stc_file_error.setForeground(new java.awt.Color(255, 0, 0));
        stc_file_error.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_title_label, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courses_info, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faculty_info, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degree_info, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personal_info, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(director_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(save_files, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancel_files, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(stc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stc_file_error)
                                            .addComponent(stc_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(stc_file_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(student_info, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stu_label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stu_file_error)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stu_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stu_file_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(director_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(login_title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(stu_file_error)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stu_file_name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(student_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stu_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(stu_file_browse, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courses_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(stc_file_error)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(faculty_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stc_file_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stc_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stc_file_browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(degree_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personal_info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(save_files, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel_files, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menuActionPerformed
        // TODO add your handling code here:
        Login_Class lcObj = new Login_Class();
        lcObj.verify(user_id);
        String type = lcObj.type;
        if (type.equals("Director")) {
            Director_Main_Menu dmmObj = new Director_Main_Menu(user_id);
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(dmmObj);
            Dimension dt = desktop.getSize();
            Dimension dmm = dmmObj.getSize();
            dmmObj.setLocation((dt.width - dmm.width) / 2, (dt.height - dmm.height) / 2);
            dmmObj.setVisible(true);
            this.dispose();
        } else {
            Admin_Main_Menu ammObj = new Admin_Main_Menu(user_id);
            JDesktopPane desktop = this.getDesktopPane();
            desktop.add(ammObj);
            Dimension dt = desktop.getSize();
            Dimension amm = ammObj.getSize();
            ammObj.setLocation((dt.width - amm.width) / 2, (dt.height - amm.height) / 2);
            ammObj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_main_menuActionPerformed

    private void director_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_director_logoutMouseClicked
        // TODO add your handling code here:
        Window win[] = java.awt.Window.getWindows();
        for (Window win1 : win) {
            win1.dispose();
        }
        Login_Form lfObj = new Login_Form();
        lfObj.setLocationRelativeTo(null);
        lfObj.pack();
        lfObj.setVisible(true);
    }//GEN-LAST:event_director_logoutMouseClicked

    private void student_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_infoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_infoActionPerformed

    private void courses_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courses_infoActionPerformed
        // TODO add your handling code here:
        Courses_Info ciObj = new Courses_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(ciObj);
        Dimension dt = desktop.getSize();
        Dimension ci = ciObj.getSize();
        ciObj.setLocation((dt.width - ci.width) / 2, (dt.height - ci.height) / 2);
        ciObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_courses_infoActionPerformed

    private void faculty_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faculty_infoActionPerformed
        // TODO add your handling code here:
        Faculty_Info fiObj = new Faculty_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(fiObj);
        Dimension dt = desktop.getSize();
        Dimension ci = fiObj.getSize();
        fiObj.setLocation((dt.width - ci.width) / 2, (dt.height - ci.height) / 2);
        fiObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_faculty_infoActionPerformed

    private void degree_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree_infoActionPerformed
        // TODO add your handling code here:
        Degree_Info diObj = new Degree_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(diObj);
        Dimension dt = desktop.getSize();
        Dimension di = diObj.getSize();
        diObj.setLocation((dt.width - di.width) / 2, (dt.height - di.height) / 2);
        diObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_degree_infoActionPerformed

    private void personal_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_infoActionPerformed
        // TODO add your handling code here:
        Personal_Info piObj = new Personal_Info(user_id);
        JDesktopPane desktop = this.getDesktopPane();
        desktop.add(piObj);
        Dimension dt = desktop.getSize();
        Dimension di = piObj.getSize();
        piObj.setLocation((dt.width - di.width) / 2, (dt.height - di.height) / 2);
        piObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_personal_infoActionPerformed

    private void stu_file_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_file_browseActionPerformed
        // TODO add your handling code here:
        int stu_file_browse = stu_file_chooser.showOpenDialog(this);
        if (stu_file_browse == JFileChooser.APPROVE_OPTION) {
            stu_file_error.setText(" ");
            stu_file = stu_file_chooser.getSelectedFile();
            String stu_name = stu_file.getName();
            String stu_file_ext = getFileExtension(stu_file);
            stu_file_path = stu_file.getAbsolutePath();
            if (stu_file_ext.equals("csv") || stu_file_ext.equals("CSV")) {
                stu_file_name.setText(stu_name);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a valid CSV file.");
            }
        }
    }//GEN-LAST:event_stu_file_browseActionPerformed

    private void stc_file_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stc_file_browseActionPerformed
        // TODO add your handling code here:
        int stc_file_browse = stc_file_chooser.showOpenDialog(this);
        if (stc_file_browse == JFileChooser.APPROVE_OPTION) {
            stc_file_error.setText(" ");
            stc_file = stc_file_chooser.getSelectedFile();
            String stc_name = stc_file.getName();
            String stc_file_ext = getFileExtension(stc_file);
            stc_file_path = stc_file.getAbsolutePath();
            if (stc_file_ext.equals("csv") || stc_file_ext.equals("CSV")) {
                stc_file_name.setText(stc_name);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a valid CSV file.");
            }
        }
    }//GEN-LAST:event_stc_file_browseActionPerformed

    private void cancel_filesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_filesActionPerformed
        // TODO add your handling code here:
        stu_file = null;
        stc_file = null;
        stu_file_name.setText("");
        stc_file_name.setText("");
        stu_file_path = "";
        stc_file_path = "";
    }//GEN-LAST:event_cancel_filesActionPerformed

    private void save_filesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_filesActionPerformed
        // TODO add your handling code here:
        if (stu_file == null) {
            stu_file_error.setText("*This file is required.");
        } else {
            if (stc_file == null) {
                stc_file_error.setText("*This file is required.");
            } else {
                Student_Info_Class sicObj = new Student_Info_Class();
                try {
                    BufferedReader br = new BufferedReader(new FileReader(stu_file_path));
                    StringTokenizer st;
                    while ((stu_file_path = br.readLine()) != null) {
                        st = new StringTokenizer(stu_file_path, ",");
                        ArrayList<String> arr = new ArrayList<>();
                        while (st.hasMoreTokens()) {
                            arr.add(st.nextToken());
                        }
                        String id = arr.get(0);
                        String deg = arr.get(1);
                        String year = arr.get(2);
                        sicObj.add_student_info(id, deg, year);
                    }
                } catch (IOException | HeadlessException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
                try {
                    BufferedReader br = new BufferedReader(new FileReader(stc_file_path));
                    StringTokenizer st;
                    while ((stc_file_path = br.readLine()) != null) {
                        st = new StringTokenizer(stc_file_path, ",");
                        ArrayList<String> arr = new ArrayList<>();
                        while (st.hasMoreTokens()) {
                            arr.add(st.nextToken());
                        }
                        String id = arr.get(0);
                        String code = arr.get(1);
                        String name = arr.get(2);
                        String year = arr.get(3);
                        String grade = arr.get(4);
                        sicObj.add_student_course(id, code, name, year, grade);
                    }
                    JOptionPane.showMessageDialog(null, "Data upload completed successfully.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_save_filesActionPerformed

    private static String getFileExtension(File file) {
        String fileName = file.getName();
        if (fileName.lastIndexOf(".") != -1 && fileName.lastIndexOf(".") != 0) {
            return fileName.substring(fileName.lastIndexOf(".") + 1);
        } else {
            return "";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancel_files;
    public javax.swing.JButton courses_info;
    public javax.swing.JButton degree_info;
    public javax.swing.JLabel director_logout;
    public javax.swing.JButton faculty_info;
    public javax.swing.JLabel login_title_label;
    public javax.swing.JButton main_menu;
    public javax.swing.JButton personal_info;
    public javax.swing.JButton save_files;
    public javax.swing.JButton stc_file_browse;
    public javax.swing.JFileChooser stc_file_chooser;
    public javax.swing.JLabel stc_file_error;
    public javax.swing.JTextField stc_file_name;
    public javax.swing.JLabel stc_label;
    public javax.swing.JButton stu_file_browse;
    public javax.swing.JFileChooser stu_file_chooser;
    public javax.swing.JLabel stu_file_error;
    public javax.swing.JTextField stu_file_name;
    public javax.swing.JLabel stu_label;
    public javax.swing.JButton student_info;
    // End of variables declaration//GEN-END:variables
}
